# Generated by Django 4.1.5 on 2023-01-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='intro',
            field=models.TextField(default='blank', max_length=500),
            preserve_default=False,
        ),
    ]
