# Generated by Django 4.1.5 on 2023-03-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_alter_lang_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatedresources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='researchresults',
            fields=[
                ('ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publishdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=5)),
                ('admissiondate', models.DateField()),
                ('major', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='lang',
        ),
    ]
