# Generated by Django 4.1.5 on 2023-03-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0005_remove_relatedresources_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchresults',
            name='publishdate',
        ),
    ]
