# Generated by Django 4.1.5 on 2023-03-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0006_remove_researchresults_publishdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchresults',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ID',
            new_name='id',
        ),
    ]
